name: FAB-IRMA Integration

on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
          pip install -r requirements.deploy.txt
      - name: Lint
        run: |
          ./scripts/linter.sh
      - name: Package Audit
        run: |
          ./scripts/package-audit.sh
      - name: Code Security Check
        run: |
          ./scripts/code-security-check.sh
